name:                MultiCategory
version:             0.1.0.0
github:              "githubuser/MultiCategory"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/MultiCategory#readme>

dependencies:
- base >= 4.7 && < 5
- xeno
- text
- bytestring
- aeson
- algebraic-graphs
- containers
- cereal
- rdf4h
- split

library:
  source-dirs: src

executables:
  MultiCategory-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MultiCategory

tests:
  MultiCategory-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MultiCategory
